version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: perntodo
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./server/database.sql:/docker-entrypoint-database.d/database.sql
    ports:
      - "5432:5432"
  server:
    build: ./server
    container_name: backend
    restart: always
    environment:
      DB_HOST: db
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: perntodo
    ports:
      - "5000:5000"
    depends_on:
      db:
        conditions: service_healthy


  client:
    build: ./client
    container_name: frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - server

volumes:
  pgdata: